jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build
        run: docker build .
name: build
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/dockerhub-description.yml
      - .github/workflows/publish.yml
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE
      - README.md
  push:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/dockerhub-description.yml
      - .github/workflows/publish.yml
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE
      - README.md
