jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build
        run: docker build .
name: Build
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - README.md
      - LICENSE
  push:
    branches: [ main ]
    paths-ignore:
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - README.md
      - LICENSE
