env:
  IMAGE_NAME: cross-debian
jobs:
  docker:
    if: github.ref_type == 'branch'
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          path: /tmp/.buildx-cache
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          context: .
          load: true
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
      - name: Move cache
        run: |
          rm -fr /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Save the built image
        run: |
          docker save \
              -o /tmp/${{ env.IMAGE_NAME }}.tar \
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
      - name: Store the saved image to cache
        uses: actions/cache@v2
        with:
          key: Built-${{ github.sha }}
          path: /tmp/${{ env.IMAGE_NAME }}.tar
  examples:
    if: github.ref_type == 'branch'
    name: Examples
    needs:
      - docker
    uses: ./.github/workflows/examples.yml
name: Build
on:
  pull_request:
  push:
