jobs:
  dockerhub:
    name: See the latest snowstep/cross-debian on DockerHub
    outputs:
      OUTDATED: ${{ steps.dockerhub-cross-debian.outputs.OUTDATED }}
    runs-on: ubuntu-latest
    steps:
      - id: dockerhub-cross-debian
        name: Compare the latest updates between snowstep/llvm and snowstep/cross-debian
        run: |
          api=https://hub.docker.com/v2/namespaces/snowstep/repositories
          for repo in llvm cross-debian; do
            last=$(curl -s $api/$repo/tags | jq -cr '.results[]|select(.name=="latest").last_updated')
            printf '%s=%s\n' $repo $last >&2
            date --date=$last "+%s"
          done | xargs | {
            read latest_llvm latest_cross_debian
            printf 'llvm=%s\n' $latest_llvm >&2
            printf 'cross_debian=%s\n' $latest_cross_debian >&2
            [[ $latest_llvm -lt $latest_cross_debian ]] \
            && printf 'OUTDATED=false\n' \
            || printf 'OUTDATED=true\n'
          } | tee -a $GITHUB_OUTPUT
        shell: bash
  publish-if-outdated:
    name: Publish if outdated
    needs:
      - dockerhub
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    uses: ./.github/workflows/publish.yml
    with:
      OUTDATED: ${{ needs.dockerhub.outputs.OUTDATED == 'true' }}
name: Check updates
on:
  schedule:
    - cron: '0 */12 * * *'
