jobs:
  dockerhub:
    name: Get the last updated timestamps of snowstep/cross-debian and snowstep/llvm on DockerHub
    outputs:
      cross-debian: ${{ steps.last-updated.outputs.cross-debian }}
      llvm: ${{ steps.last-updated.outputs.llvm }}
    runs-on: ubuntu-latest
    steps:
      - id: last-updated
        name: Get the last updated timestamps of snowstep/cross-debian and snowstep/llvm
        run: |
          api=https://hub.docker.com/v2/namespaces/snowstep/repositories
          for repo in llvm cross-debian; do
            last=$(curl -s $api/$repo/tags | jq -cr '.results[]|select(.name=="latest").last_updated')
            timestamp=$(date --date=$last "+%s")
            printf '%s=%s (%s)\n' $repo $timestamp $last >&2
            printf '%s=%s\n' $repo $timestamp
          done > $GITHUB_OUTPUT
        shell: bash
  publish-if-outdated:
    if: ${{ needs.dockerhub.outputs.cross-debian < needs.dockerhub.outputs.llvm }}
    name: Publish if outdated
    needs:
      - dockerhub
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    uses: ./.github/workflows/publish.yml
    with:
      freebsd-version: '13.1'
name: Check updates
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
