jobs:
  example:
    name: Example of ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Restore the built image from cache
        uses: actions/cache@v3
        with:
          key: Built-${{ github.sha }}
          path: /tmp/cross-debian.tar
          restore-keys: |
            Built-
      - name: Load the restored image
        run: |
          docker load \
              -i /tmp/cross-debian.tar
      - name: Build for ${{ matrix.os }}
        run: |
          docker build \
              --cache-from=/tmp/.buildx-cache \
              -f example/${{ matrix.os }}/Dockerfile \
              -t example:${{ matrix.os }} \
              .
      - name: Run the automatic build script for ${{ matrix.os }}
        run: |
          docker run \
              --rm \
              example:${{ matrix.os }} \
              ./autobuild.sh \
            | tar -xf -
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: Example-${{ matrix.os }}
          path: |
            foo-*
    strategy:
      matrix:
        os:
          - freebsd
          - linux
          - mingw
name: Examples
on:
  workflow_call:
