jobs:
  freebsd-arm:
    name: Prepare FreeBSD-${{ inputs.version }} ${{ matrix.arch }}:${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - id: cache
        name: Attempt to restore from cache
        uses: actions/cache/restore@v4
        with:
          key: FreeBSD-${{ inputs.version }}-${{ matrix.arch }}-${{ matrix.name }}
          path: ./fbsd/${{ inputs.version }}/${{ matrix.arch }}
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        name: Download ISO image
        run: |
          curl \
              -ks \
              https://download.freebsd.org/ftp/releases/arm/${{ matrix.arch }}/ISO-IMAGES/${{ inputs.version }}/FreeBSD-${{ inputs.version }}-RELEASE-arm-${{ matrix.arch }}-${{ matrix.name }}.img.xz \
            > ${{ matrix.arch }}-${{ matrix.name }}.img.xz
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        name: Decompress
        run: |
          xz -dv ${{ matrix.arch }}-${{ matrix.name }}.img.xz
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        name: Extract required files
        run: |
          device_name=$(sudo losetup --find)
          sudo losetup --partscan $device_name ${{ matrix.arch }}-${{ matrix.name }}.img
          part_name=$(sudo fdisk --list $device_name | grep 'FreeBSD$' | cut -d' ' -f1)
          offset=$(sudo fdisk --list $part_name | grep '4.2BSD' | awk '{{ print $2 }}')
          mkdir mnt
          sudo mount -t ufs -o loop,noatime,offset=$(($offset * 512)),ro,ufstype=ufs2 $part_name ./mnt
          arch_path=./fbsd/${{ inputs.version }}/${{ matrix.arch }}
          mkdir -pv $arch_path/usr/share
          sudo cp -r ./mnt/{etc,lib} $arch_path/
          sudo cp -r ./mnt/usr/{include,lib{,data}} $arch_path/usr/
          sudo rm -fr $arch_path/usr/lib/debug
          sudo cp -r ./mnt/usr/share/keys $arch_path/usr/share/
          sudo chown -R $(whoami) $arch_path
          sudo umount ./mnt
          rm -fr ./mnt
          sudo losetup --detach $device_name
          rm -f ${{ matrix.arch }}-${{ matrix.name }}.img
        shell: bash
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        name: Cache extracted files
        uses: actions/cache/save@v4
        with:
          key: FreeBSD-${{ inputs.version }}-${{ matrix.arch }}-${{ matrix.name }}
          path: ./fbsd/${{ inputs.version }}/${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: armv6
            name: RPI-B
          - arch: armv7
            name: GENERICSD
name: Prepare FreeBSD ARM
on:
  workflow_call:
    inputs:
      version:
        description: >
          The version of FreeBSD.
        required: true
        type: string
