env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/cross-debian
jobs:
  docker:
    if: github.ref_type == 'tag'
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - id: version
        name: Get the version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=$(echo "$VERSION" | sed -e 's/^v//')
          MAJOR_VERSION=$(echo $VERSION | sed -n "s/^\([0-9]*\).[0-9]*.[0-9]*$/\1/p")
          MINOR_VERSION=$(echo $VERSION | sed -n "s/^\([0-9]*.[0-9]*\).[0-9]*$/\1/p")
          echo "::set-output name=MAJOR_VERSION::$MAJOR_VERSION"
          echo "::set-output name=MINOR_VERSION::$MINOR_VERSION"
          echo "::set-output name=VERSION::$VERSION"
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v3.0.11
        with:
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          path: /tmp/.buildx-cache
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build a docker image and push it
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.MAJOR_VERSION }}
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.MINOR_VERSION }}
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
      - name: Move cache
        run: |
          rm -fr /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Patch the description to Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          short-description: Cross compile environment on Debian
          username: ${{ secrets.DOCKERHUB_USERNAME }}
name: Publish
on:
  create:
    tags:
      - 'v[0-9]+(\.[0-9]+)*'
