env:
  IMAGE_NAME: cross-debian
jobs:
  docker:
    if: github.ref_type == 'tag'
    name: Build and Publish the docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - id: meta
        name: Docker metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Restore the saved image from cache
        uses: actions/cache@v3
        with:
          key: Built-${{ github.sha }}
          path: /tmp/${{ env.IMAGE_NAME }}.tar
          restore-keys: |
            Built-
      - name: Load the restored image
        run: |
          docker load \
              -i /tmp/${{ env.IMAGE_NAME }}.tar
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Push the docker image to DockerHub
        run: |
          prefix=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          echo "${{ steps.meta.outputs.tags }}" | while read name; do
            docker tag $prefix $name
            docker push $name
          done
        shell: bash
      - name: Patch the description to Docker Hub
        run: |
          DOCKERHUB_PASSWORD="${{ secrets.DOCKERHUB_PASSWORD }}" \
          DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" \
          tools/patch-dockerhub.sh ${{ env.IMAGE_NAME }} "Cross compile environment on Debian"
name: Publish
on:
  create:
    tags:
      - v[0-9]+(\.[0-9]+)*
