env:
  IMAGE_NAME: cross-debian
jobs:
  docker:
    if: ${{ inputs.OUTDATED == 'true' }}
    name: Build and Publish the docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - id: meta
        name: Docker metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDDHHmmss'}}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Run Buildx and Push it to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
      - id: overview
        name: Load README
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('node:fs')
            fs.readFile('README.md', {}, (err, data) => {
              if (err)
                core.setFailed(err.message)
              else
                core.setOutput('content', data.toString())
            })
      - name: Patch the description
        uses: kei-g/dockerhub-patch@main
        with:
          description: Cross compile environment on Debian
          overview: |
            ${{ steps.overview.outputs.content }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repo: ${{ env.IMAGE_NAME }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
name: Publish
on:
  workflow_call:
    inputs:
      OUTDATED:
        description: 'Is necessary for update'
        required: true
        type: string
    secrets:
      DOCKERHUB_PASSWORD:
        required: true
      DOCKERHUB_USERNAME:
        required: true
