env:
  IMAGE_NAME: cross-debian
jobs:
  docker:
    if: github.ref_type == 'tag'
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - id: version
        name: Get the version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=$(echo "$VERSION" | sed -e 's/^v//')
          MAJOR_VERSION=$(echo $VERSION | sed -n "s/^\([0-9]*\).[0-9]*.[0-9]*$/\1/p")
          MINOR_VERSION=$(echo $VERSION | sed -n "s/^\([0-9]*.[0-9]*\).[0-9]*$/\1/p")
          echo "::set-output name=MAJOR_VERSION::$MAJOR_VERSION"
          echo "::set-output name=MINOR_VERSION::$MINOR_VERSION"
          echo "::set-output name=VERSION::$VERSION"
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Restore the saved image from cache
        uses: actions/cache@v2
        with:
          key: Built-${{ github.sha }}
          path: /tmp/${{ env.IMAGE_NAME }}.tar
          restore-keys: |
            Built-
      - name: Load the restored image
        run: |
          docker load \
              -i /tmp/${{ env.IMAGE_NAME }}.tar
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Push the docker image to DockerHub
        run: |
          prefix=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags=(${{ steps.version.outputs.MAJOR_VERSION }})
          tags+=(${{ steps.version.outputs.MINOR_VERSION }})
          tags+=(${{ steps.version.outputs.VERSION }})
          for tag in "$tags[@]"; do
            docker tag $prefix $prefix:$tag
            docker push $prefix:$tag
          done
        shell: bash
      - name: Patch the description to Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          short-description: Cross compile environment on Debian
          username: ${{ secrets.DOCKERHUB_USERNAME }}
name: Publish
on:
  create:
    tags:
      - v[0-9]+(\.[0-9]+)*
