env:
  IMAGE_NAME: snowstep/cross-debian
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Docker Hub Login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --password-stdin -u "${{ secrets.DOCKERHUB_USERNAME }}"
      - name: Push image to Docker Hub
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          docker build --label "org.opencontainers.image.version=$VERSION" -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $IMAGE_NAME:$VERSION
          MINOR_VERSION=$(echo $VERSION | sed -n "s/^\([0-9]*.[0-9]*\).[0-9]*$/\1/p")
          [[ ${#MINOR_VERSION} -gt 0 ]] && docker tag $IMAGE_NAME $IMAGE_NAME:$MINOR_VERSION
          MAJOR_VERSION=$(echo $VERSION | sed -n "s/^\([0-9]*\).[0-9]*.[0-9]*$/\1/p")
          [[ ${#MAJOR_VERSION} -gt 0 ]] && docker tag $IMAGE_NAME $IMAGE_NAME:$MAJOR_VERSION
          docker push $IMAGE_NAME
name: publish
on:
  create:
    tags:
      - 'v[0-9]+(\.[0-9]+)*'
